openapi: 3.0.0
info:
  title: first
  version: '1.0'
  description: first test api doc
servers:
  - url: 'http://localhost:3000'
paths:
  /x:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-x
components:
  schemas:
    uu:
      title: uu
      type: object
      properties:
        id:
          type: string
      x-examples: {}
  securitySchemes:
    Authorization:
      name: API Key
      type: apiKey
      in: header
